server:
  port: 3355

spring:
  application:
    name:  cloud-config-client #注册进Eureka服务器的微服务名

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
